FROM node:10.5.0

MAINTAINER yuliang <yu.liang@freelog.com>

RUN mkdir -p /data/freelog-event-service

WORKDIR /data/freelog-event-service

COPY . /data/freelog-event-service

RUN npm install

ENV NODE_ENV test
ENV EGG_SERVER_ENV test
ENV PORT 5010

EXPOSE 5010

CMD [ "npm", "start" ]
