FROM node:14.6.0-alpine

MAINTAINER yuliang <yu.liang@freelog.com>

RUN mkdir -p /data/freelog-contract-service

WORKDIR /data/freelog-contract-service

COPY . /data/freelog-contract-service

RUN npm install --production

ENV NODE_ENV test
ENV EGG_SERVER_ENV test
ENV PORT 5109
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

EXPOSE 5109

CMD [ "npm", "start" ]
